In [4]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [6]:
import pandas as pd

# Load dataset
df = pd.read_csv('/content/SuperStoreOrders[1].csv', encoding='latin1')

# Fix column names
df.columns = df.columns.str.replace('ï»¿', '')
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Cleaning
df.drop_duplicates(inplace=True)
df.fillna(0, inplace=True)

# ✅ Handle mixed date formats (FINAL FIX)
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=True)
df['ship_date'] = pd.to_datetime(df['ship_date'], format='mixed', dayfirst=True)

# Check
print(df.dtypes)
df.head()

order_id                  object
order_date        datetime64[ns]
ship_date         datetime64[ns]
ship_mode                 object
customer_name             object
segment                   object
state                     object
country                   object
market                    object
region                    object
product_id                object
category                  object
sub_category              object
product_name              object
sales                     object
quantity                   int64
discount                 float64
profit                   float64
shipping_cost            float64
order_priority            object
year                     float64
dtype: object

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011.0
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011.0
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011.0
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011.0
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011.0

In [14]:
df[df['profit'] < 0].groupby('category')['profit'].sum()

category
Furniture         -249920.21600
Office Supplies   -181050.66110
Technology        -200088.58122
Name: profit, dtype: float64

In [15]:
df.to_csv("final_sales.csv", index=False)

-------------------------------------------------------

In [16]:
from google.colab import files
uploaded = files.upload()

Saving dashboard.png to dashboard.png

In [17]:
import os
os.listdir()

['.config',
 'final_sales.csv',
 'SuperStoreOrders[1].csv',
 'dashboard.png',
 'sample_data']

In [21]:
!git clone https://bhaskar3512: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@github.com/bhaskar3512/superstore-data-analysis.git

Cloning into 'superstore-data-analysis'...
warning: You appear to have cloned an empty repository.

In [22]:
%cd superstore-data-analysis

/content/superstore-data-analysis

In [23]:
!cp /content/final_sales.csv .
!cp /content/SuperStoreOrders[1].csv .
!cp /content/dashboard.png .

In [24]:
!mv "SuperStoreOrders[1].csv" superstore_orders.csv
!mv final_sales.csv cleaned_data.csv

In [25]:
!ls

cleaned_data.csv  dashboard.png  superstore_orders.csv

In [26]:
!git add .

In [28]:
!git config --global user.name "bhaskar3512"
!git config --global user.email "bhaskarharugade4@gmail.com"

In [29]:
!git add .
!git commit -m "Added dataset and dashboard"
!git push

[main (root-commit) eee235e] Added dataset and dashboard
 3 files changed, 86132 insertions(+)
 create mode 100644 cleaned_data.csv
 create mode 100644 dashboard.png
 create mode 100644 superstore_orders.csv
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 3.05 MiB | 1.70 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/bhaskar3512/superstore-data-analysis.git
 * [new branch]      main -> main